### ISSUE TITLE
create readme file

### ISSUE THREAD

**Issue by vic-test-1** [vic-test-1/commiteth-test#1]

**Comment by commiteth** [comment]
![Contract deploying](https://commiteth.com:444/img/deploying_contract.png)

**Comment by commiteth** [comment]
Current balance: 1.0 ETH
Contract address: [0x26f895318c920e80da4a83cc534719fa9ba1d6bf](https://ropsten.etherscan.io/address/0x26f895318c920e80da4a83cc534719fa9ba1d6bf)
![QR Code](https://commiteth.com:444/qr/vic-test-1/commiteth-test/bounty/1/a8fbfbd1790808caeef8dad752ba520c36c2e5a1000c80b1b7d7808e087b2165/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://commiteth.com:444](https://commiteth.com:444)
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.

**Comment by vic-test-1** [comment]
closing and try again
